apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver
  type: LoadBalancer
  ports:
  - name: goserver-service
    port: 80
    targetPort: 8000
    protocol: TCP

#O LoadBalancer é uma opção quando você deseja distribuir o tráfego externo entre os pods do serviço de forma balanceada e quando está usando um provedor de nuvem que oferece esse tipo de serviço de balanceamento de carga. 