apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver
  type: ClusterIP
  ports:
  - name: goserver-service
    port: 80
    targetPort: 8000
    protocol: TCP

# kubectl apply -f ./service.yml
# kubectl get svc
# kubectl port-forward svc/nome_do_serivce porta_mapeada:porta_mapeada

#port é a porta do service, targetPort é a porta do container
