apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: demo
  labels:
    app: demo
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 2
  template:
    metadata:
    labels:
      app: "demo"
    spec:
      containers:
        - name: demo
          image: "hugo/demo:latest"
          env:
            - name: NAME
              value: "valor" 
            - name: AGE
              value: "24" 