apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP

#port is service port, targetPort is the containerport
