apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 7
  template:
    metadata:
    labels:
      app: "demo"
    spec:
      containers:
        - name: demo
          image: "hugo/demo:latest"